### ISSUE TITLE
No download

### ISSUE THREAD

**Issue by koff75** [williammuff/djcityuserscript#2]
When clicking on the down arrow, I have this kind of error on my console : 

POST http://www.djcity.com/record-pool_track.aspx?rid=***** 500 (Internal Server Error)
Error with post request to rate track (Url :/record-pool_track.aspx?rid=**** Post Data:__EVENTTARGET=&__EVENTARGUMENT=&__VIEWSTATE=%20&__EVENTVALIDATION=3C%2F%2FDTD%20XHTML%201.0%20Strict%2F%2FEN&ctl00%24PageContent%24rating=3&ctl00%24PageContent%24like=&ctl00%24PageContent%24submit=

Thanks

**Comment by williammuff** [comment]
This has been resolved.
